import {
  ORGANIZACAO_TCHE_ID,
  type MockV2State,
} from '../domain/contractsV2';
import type { PeriodoProdutivoMetadata } from '../types/periodoProdutivo';

export const MOCK_V2_DEMO_QA_IDS = {
  usuarioProdutorAtivo: 'usr_qa_produtor_ativo',
  usuarioProdutorPendente: 'usr_qa_produtor_pendente',
  usuarioProdutorInativo: 'usr_qa_produtor_inativo',
  usuarioColaboradorInativo: 'usr_qa_colaborador_inativo',
  produtorAtivo: 'produtor_qa_ativo',
  produtorPendente: 'produtor_qa_pendente',
  produtorInativo: 'produtor_qa_inativo',
  propriedadeOperacional: 'propriedade_qa_cenarios_operacionais',
  propriedadeSemTalhoes: 'propriedade_qa_sem_talhoes',
  propriedadeInativa: 'propriedade_qa_inativa',
  talhaoAtivo: 'talhao_qa_sem_geometria_ativo',
  talhaoInativo: 'talhao_qa_sem_geometria_inativo',
} as const;

export const MOCK_V2_DEMO_QA_CREDENTIALS = [
  {
    usuario_id: MOCK_V2_DEMO_QA_IDS.usuarioProdutorAtivo,
    email: 'qa.produtor.ativo@example.com',
    senha: 'qaAtivo123',
  },
  {
    usuario_id: MOCK_V2_DEMO_QA_IDS.usuarioProdutorPendente,
    email: 'qa.produtor.pendente@example.com',
    senha: 'qaPendente123',
  },
  {
    usuario_id: MOCK_V2_DEMO_QA_IDS.usuarioProdutorInativo,
    email: 'qa.produtor.inativo@example.com',
    senha: 'qaInativo123',
  },
  {
    usuario_id: MOCK_V2_DEMO_QA_IDS.usuarioColaboradorInativo,
    email: 'qa.colaborador.inativo@example.com',
    senha: 'qaColabInativo123',
  },
] as const;

const appendMissingById = <T extends { id: string }>(current: T[], additions: T[]): T[] => {
  const existingIds = new Set(current.map((record) => record.id));
  return [
    ...current,
    ...additions.filter((record) => !existingIds.has(record.id)),
  ];
};

const mergeOperationalQaRecords = <T extends { id: string; talhao_nome?: unknown }>(
  current: T[],
  additions: T[]
): T[] => {
  const additionsById = new Map(additions.map((record) => [record.id, record]));
  return appendMissingById(
    current.map((record) => {
      const addition = additionsById.get(record.id);
      if (!addition || record.talhao_nome || !addition.talhao_nome) return record;
      return { ...record, talhao_nome: addition.talhao_nome };
    }),
    additions
  );
};

const buildQaCoverage = (base: MockV2State): Omit<MockV2State, 'dataset' | 'organizacao'> => {
  const referenceProperty = base.propriedades[0];
  if (!referenceProperty) {
    throw new Error('MockV2.QA: o dataset base precisa conter ao menos uma Propriedade.');
  }

  const referenceTitular = base.produtores.find(
    (producer) => producer.id === referenceProperty.titular_id
  );
  if (!referenceTitular) {
    throw new Error('MockV2.QA: Titular de referência não encontrado.');
  }

  const propertyLocation = {
    municipio_id: referenceProperty.municipio_id,
    municipio_nome: referenceProperty.municipio_nome,
    uf_id: referenceProperty.uf_id,
    uf_sigla: referenceProperty.uf_sigla,
  };
  const propertyId = MOCK_V2_DEMO_QA_IDS.propriedadeOperacional;
  const talhaoId = MOCK_V2_DEMO_QA_IDS.talhaoAtivo;
  const actor = {
    id: 'usr_colaborador_victor',
    nome: 'Victor',
  };

  const usuarios: MockV2State['usuarios'] = [
    {
      id: MOCK_V2_DEMO_QA_IDS.usuarioProdutorAtivo,
      organizacao_id: ORGANIZACAO_TCHE_ID,
      nome: '[QA] Produtor Ativo',
      email: 'qa.produtor.ativo@example.com',
      perfil: 'produtor',
      status: 'ativo',
      telefone: '(65) 99999-1001',
      observacoes: 'Usuário sintético para a rodada final de QA.',
    },
    {
      id: MOCK_V2_DEMO_QA_IDS.usuarioProdutorPendente,
      organizacao_id: ORGANIZACAO_TCHE_ID,
      nome: '[QA] Produtor Pendente',
      email: 'qa.produtor.pendente@example.com',
      perfil: 'produtor',
      status: 'pendente',
      observacoes: 'Usuário sintético para validar bloqueio de acesso pendente.',
    },
    {
      id: MOCK_V2_DEMO_QA_IDS.usuarioProdutorInativo,
      organizacao_id: ORGANIZACAO_TCHE_ID,
      nome: '[QA] Produtor Inativo',
      email: 'qa.produtor.inativo@example.com',
      perfil: 'produtor',
      status: 'inativo',
      observacoes: 'Usuário sintético para validar bloqueio de acesso inativo.',
    },
    {
      id: MOCK_V2_DEMO_QA_IDS.usuarioColaboradorInativo,
      organizacao_id: ORGANIZACAO_TCHE_ID,
      nome: '[QA] Colaborador Inativo',
      email: 'qa.colaborador.inativo@example.com',
      perfil: 'colaborador',
      status: 'inativo',
      observacoes: 'Usuário sintético sem escopo ativo.',
    },
  ];

  const produtores: MockV2State['produtores'] = [
    {
      id: MOCK_V2_DEMO_QA_IDS.produtorAtivo,
      organizacao_id: ORGANIZACAO_TCHE_ID,
      usuario_id: MOCK_V2_DEMO_QA_IDS.usuarioProdutorAtivo,
      nome: '[QA] Produtor Ativo',
      status: 'ativo',
    },
    {
      id: MOCK_V2_DEMO_QA_IDS.produtorPendente,
      organizacao_id: ORGANIZACAO_TCHE_ID,
      usuario_id: MOCK_V2_DEMO_QA_IDS.usuarioProdutorPendente,
      nome: '[QA] Produtor Pendente',
      status: 'inativo',
    },
    {
      id: MOCK_V2_DEMO_QA_IDS.produtorInativo,
      organizacao_id: ORGANIZACAO_TCHE_ID,
      usuario_id: MOCK_V2_DEMO_QA_IDS.usuarioProdutorInativo,
      nome: '[QA] Produtor Inativo',
      status: 'inativo',
    },
  ];

  const propriedades: MockV2State['propriedades'] = [
    {
      id: propertyId,
      organizacao_id: ORGANIZACAO_TCHE_ID,
      titular_id: MOCK_V2_DEMO_QA_IDS.produtorAtivo,
      nome: '[QA] Propriedade Cenários Operacionais',
      ...propertyLocation,
      area_total: 1234.56,
      cultura_principal: 'Soja',
      status: 'ativa',
    },
    {
      id: MOCK_V2_DEMO_QA_IDS.propriedadeSemTalhoes,
      organizacao_id: ORGANIZACAO_TCHE_ID,
      titular_id: MOCK_V2_DEMO_QA_IDS.produtorAtivo,
      nome: '[QA] Propriedade Sem Talhões',
      ...propertyLocation,
      status: 'ativa',
    },
    {
      id: MOCK_V2_DEMO_QA_IDS.propriedadeInativa,
      organizacao_id: ORGANIZACAO_TCHE_ID,
      titular_id: MOCK_V2_DEMO_QA_IDS.produtorAtivo,
      nome: '[QA] Propriedade Inativa',
      ...propertyLocation,
      area_total: 78.9,
      cultura_principal: 'Milho',
      status: 'inativa',
    },
  ];

  const usuarios_propriedades: MockV2State['usuarios_propriedades'] = [
    ...propriedades.map((property) => ({
      id: `vinculo_qa_titular_${property.id}`,
      organizacao_id: ORGANIZACAO_TCHE_ID,
      usuario_id: MOCK_V2_DEMO_QA_IDS.usuarioProdutorAtivo,
      propriedade_id: property.id,
      tipo_vinculo: 'titular' as const,
      status: 'ativo' as const,
    })),
    {
      id: 'vinculo_qa_victor_operacional',
      organizacao_id: ORGANIZACAO_TCHE_ID,
      usuario_id: 'usr_colaborador_victor',
      propriedade_id: propertyId,
      tipo_vinculo: 'colaborador',
      status: 'ativo',
    },
    {
      id: 'vinculo_qa_victor_sem_talhoes',
      organizacao_id: ORGANIZACAO_TCHE_ID,
      usuario_id: 'usr_colaborador_victor',
      propriedade_id: MOCK_V2_DEMO_QA_IDS.propriedadeSemTalhoes,
      tipo_vinculo: 'colaborador',
      status: 'ativo',
    },
    {
      id: 'vinculo_qa_bruna_propriedade_inativa',
      organizacao_id: ORGANIZACAO_TCHE_ID,
      usuario_id: 'usr_colaborador_bruna_brito',
      propriedade_id: MOCK_V2_DEMO_QA_IDS.propriedadeInativa,
      tipo_vinculo: 'colaborador',
      status: 'ativo',
    },
    {
      id: 'vinculo_qa_bruna_operacional_inativo',
      organizacao_id: ORGANIZACAO_TCHE_ID,
      usuario_id: 'usr_colaborador_bruna_brito',
      propriedade_id: propertyId,
      tipo_vinculo: 'colaborador',
      status: 'inativo',
    },
    {
      id: 'vinculo_qa_produtor_autorizado',
      organizacao_id: ORGANIZACAO_TCHE_ID,
      usuario_id: referenceTitular.usuario_id,
      propriedade_id: propertyId,
      tipo_vinculo: 'usuario_autorizado',
      status: 'ativo',
    },
  ];

  const talhoes: MockV2State['talhoes'] = [
    {
      id: talhaoId,
      organizacao_id: ORGANIZACAO_TCHE_ID,
      propriedade_id: propertyId,
      nome: '[QA] Talhão sem geometria',
      codigo: 'QA-SG-01',
      status: 'ativo',
    },
    {
      id: MOCK_V2_DEMO_QA_IDS.talhaoInativo,
      organizacao_id: ORGANIZACAO_TCHE_ID,
      propriedade_id: propertyId,
      nome: '[QA] Talhão inativo',
      codigo: 'QA-IN-02',
      status: 'inativo',
    },
  ];

  const visitEvent = (id: string, type: string, occurredAt: string, version = 1) => ({
    evento_id: `${id}_evento_${version}`,
    tipo: type,
    propriedade_id: propertyId,
    versao: version,
    ocorrido_em: occurredAt,
    ator_usuario_id: actor.id,
    ator_nome: actor.nome,
  });
  const visitas: MockV2State['visitas'] = [
    {
      id: 'visita_qa_agendada_futura',
      organizacao_id: ORGANIZACAO_TCHE_ID,
      propriedade_id: propertyId,
      talhao_id: talhaoId,
      talhao_nome: '[QA] Talhão sem geometria',
      tecnico_responsavel: actor.nome,
      responsavel_usuario_id: actor.id,
      data_visita: '2026-08-18T13:00:00.000Z',
      agendada_para: '2026-08-18T13:00:00.000Z',
      objetivo: 'consultoria',
      status: 'agendada',
      observacoes: '[QA] Agendamento futuro com Talhão sem geometria.',
      fotos: [],
      criada_por_usuario_id: actor.id,
      criada_por_nome: actor.nome,
      criada_em: '2026-08-06T12:00:00.000Z',
      versao_atual: 1,
      eventos_visita: [visitEvent('visita_qa_agendada_futura', 'visita_agendada', '2026-08-06T12:00:00.000Z')],
      complementos_visita: [],
      registro_legado: false,
    },
    {
      id: 'visita_qa_agendada_atrasada',
      organizacao_id: ORGANIZACAO_TCHE_ID,
      propriedade_id: propertyId,
      tecnico_responsavel: actor.nome,
      responsavel_usuario_id: actor.id,
      data_visita: '2026-07-30T13:00:00.000Z',
      agendada_para: '2026-07-30T13:00:00.000Z',
      objetivo: 'coleta_solo',
      status: 'agendada',
      observacoes: '[QA] Visita vencida para validar destaque e filtros.',
      fotos: [],
      criada_por_usuario_id: actor.id,
      criada_por_nome: actor.nome,
      criada_em: '2026-07-20T12:00:00.000Z',
      versao_atual: 1,
      eventos_visita: [visitEvent('visita_qa_agendada_atrasada', 'visita_agendada', '2026-07-20T12:00:00.000Z')],
      complementos_visita: [],
      registro_legado: false,
    },
    {
      id: 'visita_qa_realizada',
      organizacao_id: ORGANIZACAO_TCHE_ID,
      propriedade_id: propertyId,
      talhao_id: talhaoId,
      talhao_nome: '[QA] Talhão sem geometria',
      tecnico_responsavel: actor.nome,
      responsavel_usuario_id: actor.id,
      responsavel_executante_usuario_id: actor.id,
      responsavel_executante_nome: actor.nome,
      data_visita: '2026-08-01T13:00:00.000Z',
      inicio_real_em: '2026-08-01T13:05:00.000Z',
      concluida_em: '2026-08-01T15:10:00.000Z',
      concluida_por_usuario_id: actor.id,
      concluida_por_nome: actor.nome,
      objetivo: 'avaliacao_cultivo',
      status: 'realizada',
      observacoes: '[QA] Avaliação com registro moderno e foto remota demonstrativa.',
      recomendacoes: 'Reavaliar o estande em sete dias.',
      resumo_conclusao: 'Avaliação concluída sem ocorrência crítica.',
      clima: 'Ensolarado',
      fotos: ['https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=900&q=70'],
      criada_por_usuario_id: actor.id,
      criada_por_nome: actor.nome,
      criada_em: '2026-07-28T12:00:00.000Z',
      versao_atual: 2,
      eventos_visita: [
        visitEvent('visita_qa_realizada', 'visita_agendada', '2026-07-28T12:00:00.000Z'),
        visitEvent('visita_qa_realizada', 'visita_concluida', '2026-08-01T15:10:00.000Z', 2),
      ],
      complementos_visita: [],
      registro_legado: false,
    },
    {
      id: 'visita_qa_cancelada',
      organizacao_id: ORGANIZACAO_TCHE_ID,
      propriedade_id: propertyId,
      tecnico_responsavel: actor.nome,
      responsavel_usuario_id: actor.id,
      data_visita: '2026-08-03T13:00:00.000Z',
      objetivo: 'entrega_material',
      status: 'cancelada',
      observacoes: '[QA] Cancelamento com motivo informado.',
      cancelamento_motivo_codigo: 'indisponibilidade_produtor',
      cancelamento_motivo_descricao: 'Produtor indisponível na data combinada.',
      cancelada_em: '2026-08-02T16:00:00.000Z',
      cancelada_por_usuario_id: actor.id,
      cancelada_por_nome: actor.nome,
      fotos: [],
      criada_por_usuario_id: actor.id,
      criada_por_nome: actor.nome,
      criada_em: '2026-07-29T12:00:00.000Z',
      versao_atual: 2,
      eventos_visita: [
        visitEvent('visita_qa_cancelada', 'visita_agendada', '2026-07-29T12:00:00.000Z'),
        visitEvent('visita_qa_cancelada', 'visita_cancelada', '2026-08-02T16:00:00.000Z', 2),
      ],
      complementos_visita: [],
      registro_legado: false,
    },
    {
      id: 'visita_qa_anulada',
      organizacao_id: ORGANIZACAO_TCHE_ID,
      propriedade_id: propertyId,
      tecnico_responsavel: actor.nome,
      responsavel_usuario_id: actor.id,
      data_visita: '2026-07-22T13:00:00.000Z',
      objetivo: 'outro',
      status: 'anulada',
      observacoes: '[QA] Registro anulado para validar histórico e exclusão das listas ativas.',
      anulacao_motivo: 'Registro demonstrativo criado em duplicidade.',
      anulada_em: '2026-07-22T14:00:00.000Z',
      anulada_por_usuario_id: actor.id,
      anulada_por_nome: actor.nome,
      fotos: [],
      criada_por_usuario_id: actor.id,
      criada_por_nome: actor.nome,
      criada_em: '2026-07-22T12:00:00.000Z',
      versao_atual: 2,
      eventos_visita: [
        visitEvent('visita_qa_anulada', 'visita_agendada', '2026-07-22T12:00:00.000Z'),
        visitEvent('visita_qa_anulada', 'visita_anulada', '2026-07-22T14:00:00.000Z', 2),
      ],
      complementos_visita: [],
      registro_legado: false,
    },
  ];

  const cadernoBase = {
    organizacao_id: ORGANIZACAO_TCHE_ID,
    propriedade_id: propertyId,
    responsavel_usuario_id: actor.id,
    colaborador_responsavel: actor.nome,
    criado_por_user_id: actor.id,
    criado_por_nome: actor.nome,
    origem_registro: 'equipe',
    registro_legado: false,
  };
  const cadernoEvent = (id: string, type: string, occurredAt: string, version = 1) => ({
    evento_id: `${id}_evento_${version}`,
    tipo: type,
    propriedade_id: propertyId,
    versao: version,
    ocorrido_em: occurredAt,
    ator_usuario_id: actor.id,
    ator_nome: actor.nome,
  });
  const cadernos: MockV2State['cadernos'] = [
    {
      ...cadernoBase,
      id: 'caderno_qa_observacao_rascunho',
      data_atividade: '2026-08-06T14:00:00.000Z',
      data_criacao: '2026-08-06T14:00:00.000Z',
      tipo_atividade: 'observacao',
      observacoes: '[QA] Rascunho visível somente para o autor.',
      visivel_para_produtor: false,
      fotos: [],
      estado_caderno: 'rascunho',
      versao_atual: 1,
      eventos_caderno: [cadernoEvent('caderno_qa_observacao_rascunho', 'rascunho_criado', '2026-08-06T14:00:00.000Z')],
      complementos_caderno: [],
    },
    {
      ...cadernoBase,
      id: 'caderno_qa_plantio_registrado',
      talhao_id: talhaoId,
      talhao_nome: '[QA] Talhão sem geometria',
      data_atividade: '2026-07-10T13:00:00.000Z',
      data_criacao: '2026-07-10T13:00:00.000Z',
      tipo_atividade: 'plantio',
      operacao: 'Plantio direto',
      periodo_produtivo_id: 'periodo_qa_safra_soja',
      periodo_produtivo_label: 'Safra • Soja • 2026/2027',
      tipo_periodo: 'safra',
      cultura_periodo: 'Soja',
      ano_agricola: '2026/2027',
      condicoes_clima: 'Solo úmido; céu parcialmente nublado.',
      observacoes: '[QA] Plantio registrado com período e Talhão.',
      visivel_para_produtor: true,
      fotos: [],
      estado_caderno: 'registrado',
      versao_atual: 1,
      registrado_em: '2026-07-10T13:30:00.000Z',
      registrado_por_usuario_id: actor.id,
      registrado_por_nome: actor.nome,
      eventos_caderno: [cadernoEvent('caderno_qa_plantio_registrado', 'registro_enviado', '2026-07-10T13:30:00.000Z')],
      complementos_caderno: [],
    },
    {
      ...cadernoBase,
      id: 'caderno_qa_aplicacao_localizacao',
      talhao_id: talhaoId,
      talhao_nome: '[QA] Talhão sem geometria',
      data_atividade: '2026-07-25T13:00:00.000Z',
      data_criacao: '2026-07-25T13:00:00.000Z',
      tipo_atividade: 'aplicacao',
      produtos_utilizados: ['Produto QA A', 'Produto QA B'],
      dosagem: '2,5 L/ha',
      area_aplicada: 42.5,
      condicoes_clima: 'Vento fraco; 24 °C.',
      observacoes: '[QA] Aplicação com localização, mas Talhão propositalmente sem geometria.',
      localizacao_latitude: -12.6812,
      localizacao_longitude: -55.6884,
      localizacao_accuracy: 8,
      localizacao_captured_at: '2026-07-25T13:02:00.000Z',
      localizacao_captured_by: actor.id,
      localizacao_origem: 'foreground_explicit',
      visivel_para_produtor: true,
      fotos: [],
      estado_caderno: 'registrado',
      versao_atual: 2,
      registrado_em: '2026-07-25T13:15:00.000Z',
      registrado_por_usuario_id: actor.id,
      registrado_por_nome: actor.nome,
      eventos_caderno: [
        cadernoEvent('caderno_qa_aplicacao_localizacao', 'registro_enviado', '2026-07-25T13:15:00.000Z'),
        cadernoEvent('caderno_qa_aplicacao_localizacao', 'complemento_adicionado', '2026-07-26T10:00:00.000Z', 2),
      ],
      complementos_caderno: [{
        complemento_id: 'complemento_qa_aplicacao_1',
        propriedade_id: propertyId,
        texto: 'Conferência posterior sem divergência.',
        visivel_para_produtor: true,
        criado_em: '2026-07-26T10:00:00.000Z',
        criado_por_usuario_id: actor.id,
        criado_por_nome: actor.nome,
      }],
    },
    {
      ...cadernoBase,
      id: 'caderno_qa_colheita_arquivada',
      talhao_id: talhaoId,
      talhao_nome: '[QA] Talhão sem geometria',
      data_atividade: '2026-06-20T13:00:00.000Z',
      data_criacao: '2026-06-20T13:00:00.000Z',
      tipo_atividade: 'colheita',
      periodo_produtivo_id: 'periodo_qa_safrinha_milho',
      periodo_produtivo_label: 'Safrinha • Milho • 2025/2026',
      tipo_periodo: 'safrinha',
      cultura_periodo: 'Milho',
      ano_agricola: '2025/2026',
      area_aplicada: 38,
      produtividade: 112.4,
      condicoes_clima: 'Tempo seco.',
      observacoes: '[QA] Colheita arquivada para validar filtros de estado.',
      visivel_para_produtor: true,
      fotos: [],
      estado_caderno: 'arquivado',
      versao_atual: 2,
      registrado_em: '2026-06-20T17:00:00.000Z',
      registrado_por_usuario_id: actor.id,
      registrado_por_nome: actor.nome,
      eventos_caderno: [
        cadernoEvent('caderno_qa_colheita_arquivada', 'registro_enviado', '2026-06-20T17:00:00.000Z'),
        cadernoEvent('caderno_qa_colheita_arquivada', 'registro_arquivado', '2026-06-25T12:00:00.000Z', 2),
      ],
      complementos_caderno: [],
    },
    {
      ...cadernoBase,
      id: 'caderno_qa_ocorrencia_oculta',
      data_atividade: '2026-08-02T13:00:00.000Z',
      data_criacao: '2026-08-02T13:00:00.000Z',
      tipo_atividade: 'ocorrencia',
      observacoes: '[QA] Ocorrência interna não visível para o Produtor.',
      visivel_para_produtor: false,
      fotos: [],
      estado_caderno: 'registrado',
      versao_atual: 1,
      registrado_em: '2026-08-02T13:10:00.000Z',
      registrado_por_usuario_id: actor.id,
      registrado_por_nome: actor.nome,
      eventos_caderno: [cadernoEvent('caderno_qa_ocorrencia_oculta', 'registro_enviado', '2026-08-02T13:10:00.000Z')],
      complementos_caderno: [],
    },
    {
      ...cadernoBase,
      id: 'caderno_qa_outro_anulado',
      data_atividade: '2026-07-15T13:00:00.000Z',
      data_criacao: '2026-07-15T13:00:00.000Z',
      tipo_atividade: 'outro',
      observacoes: '[QA] Registro anulado para validar histórico.',
      visivel_para_produtor: true,
      fotos: [],
      estado_caderno: 'anulado',
      versao_atual: 2,
      registrado_em: '2026-07-15T13:10:00.000Z',
      registrado_por_usuario_id: actor.id,
      registrado_por_nome: actor.nome,
      eventos_caderno: [
        cadernoEvent('caderno_qa_outro_anulado', 'registro_enviado', '2026-07-15T13:10:00.000Z'),
        cadernoEvent('caderno_qa_outro_anulado', 'registro_anulado', '2026-07-16T09:00:00.000Z', 2),
      ],
      complementos_caderno: [],
    },
  ];

  const assetRoot = 'asset://mapas/sela-prata-i/2025/fertilidade';
  const materialBase = {
    organizacao_id: ORGANIZACAO_TCHE_ID,
    propriedade_id: propertyId,
    categoria: 'fertilidade',
    categoria_label: 'Fertilidade',
    ano: 2025,
    safra: '2025/2026',
    profundidade: '10–20 cm',
    status: 'ativo',
    visivel_para_produtor: true,
    disponivel_download: true,
    disponivel_offline: true,
    data_criacao: '2026-08-01T12:00:00.000Z',
    observacoes: '[QA] Material sintético baseado em asset demonstrativo embarcado.',
  };
  const materiais: MockV2State['materiais'] = [
    ['ph', 'pH', 'ph_10a20.png'],
    ['argila', 'Argila', 'ar_10a20.png'],
    ['materia_organica', 'Matéria orgânica', 'mo_10a20.png'],
    ['fosforo', 'Fósforo', 'pp_10a20.png'],
    ['potassio', 'Potássio', 'kk_10a20.png'],
  ].map(([elemento, label, file]) => ({
    ...materialBase,
    id: `material_qa_fertilidade_${elemento}`,
    titulo: `[QA] Mapa de ${label}`,
    elemento,
    elemento_label: label,
    tipo_material: 'diagnostico',
    arquivo_nome_original: file,
    arquivo_url: `${assetRoot}/${file}`,
    formato_arquivo: 'png',
    versao: 1,
  }));
  materiais.push(
    {
      id: 'material_qa_correcao_pdf_indisponivel',
      organizacao_id: ORGANIZACAO_TCHE_ID,
      propriedade_id: propertyId,
      titulo: '[QA] Recomendação de correção — arquivo indisponível',
      categoria: 'correcao',
      categoria_label: 'Correção de solo',
      ano: 2026,
      safra: '2026/2027',
      arquivo_nome_original: 'qa-correcao-indisponivel.pdf',
      arquivo_url: 'file:///qa/arquivo-inexistente/qa-correcao-indisponivel.pdf',
      formato_arquivo: 'pdf',
      status: 'ativo',
      visivel_para_produtor: true,
      disponivel_download: true,
      disponivel_offline: false,
      data_criacao: '2026-08-02T12:00:00.000Z',
      observacoes: '[QA] Cenário controlado de arquivo ausente; não representa documento agronômico real.',
      versao: 1,
    },
    {
      id: 'material_qa_prescricao_zip_indisponivel',
      organizacao_id: ORGANIZACAO_TCHE_ID,
      propriedade_id: propertyId,
      talhao_id: talhaoId,
      talhao_nome: '[QA] Talhão sem geometria',
      titulo: '[QA] Prescrição ZIP — arquivo indisponível',
      categoria: 'prescricao',
      categoria_label: 'Prescrição',
      ano: 2026,
      safra: '2026/2027',
      arquivo_nome_original: 'qa-prescricao-indisponivel.zip',
      arquivo_url: 'file:///qa/arquivo-inexistente/qa-prescricao-indisponivel.zip',
      formato_arquivo: 'zip',
      status: 'ativo',
      visivel_para_produtor: false,
      disponivel_download: true,
      disponivel_offline: false,
      data_criacao: '2026-08-02T12:00:00.000Z',
      observacoes: '[QA] Cenário controlado de ZIP ausente e restrito à equipe.',
      versao: 1,
    },
    {
      id: 'material_qa_rascunho_oculto_catalogo',
      organizacao_id: ORGANIZACAO_TCHE_ID,
      propriedade_id: propertyId,
      titulo: '[QA] Material em rascunho',
      categoria: 'fertilidade',
      categoria_label: 'Fertilidade',
      ano: 2026,
      arquivo_nome_original: 'qa-rascunho.png',
      formato_arquivo: 'png',
      status: 'rascunho',
      visivel_para_produtor: false,
      disponivel_download: false,
      disponivel_offline: false,
      data_criacao: '2026-08-03T12:00:00.000Z',
      observacoes: '[QA] Deve permanecer fora do catálogo publicado.',
      versao: 1,
    }
  );

  return {
    usuarios,
    produtores,
    propriedades,
    usuarios_propriedades,
    talhoes,
    visitas,
    cadernos,
    materiais,
  };
};

/**
 * Complementa o mesmo contrato v2 sem substituir registros existentes.
 * Colisões de ID preservam o dado já instalado, inclusive alterações feitas durante QA.
 */
export const mergeMockV2DemoQaCoverage = (state: MockV2State): MockV2State => {
  const qa = buildQaCoverage(state);
  return {
    ...state,
    usuarios: appendMissingById(state.usuarios, qa.usuarios),
    produtores: appendMissingById(state.produtores, qa.produtores),
    propriedades: appendMissingById(state.propriedades, qa.propriedades),
    usuarios_propriedades: appendMissingById(
      state.usuarios_propriedades,
      qa.usuarios_propriedades
    ),
    talhoes: appendMissingById(state.talhoes, qa.talhoes),
    visitas: mergeOperationalQaRecords(state.visitas, qa.visitas),
    cadernos: mergeOperationalQaRecords(state.cadernos, qa.cadernos),
    materiais: mergeOperationalQaRecords(state.materiais, qa.materiais),
  };
};

export const MOCK_V2_DEMO_QA_PERIODOS: PeriodoProdutivoMetadata[] = [
  {
    id: 'periodo_qa_safra_soja',
    propriedade_id: MOCK_V2_DEMO_QA_IDS.propriedadeOperacional,
    nome_propriedade: '[QA] Propriedade Cenários Operacionais',
    tipo_periodo: 'safra',
    tipo_periodo_label: 'Safra',
    cultura: 'Soja',
    ano_agricola: '2026/2027',
    label: 'Safra • Soja • 2026/2027',
    data_inicio: '2026-09-15T12:00:00.000Z',
    data_fim: '2027-02-28T12:00:00.000Z',
    status: 'planejada',
    observacoes: '[QA] Período planejado.',
    criado_por_user_id: 'usr_colaborador_victor',
    criado_por_nome: 'Victor',
    criado_em: '2026-08-01T12:00:00.000Z',
    atualizado_em: '2026-08-01T12:00:00.000Z',
    registro_status: 'ativo',
    origem: 'local',
    versao: 1,
  },
  {
    id: 'periodo_qa_safrinha_milho',
    propriedade_id: MOCK_V2_DEMO_QA_IDS.propriedadeOperacional,
    nome_propriedade: '[QA] Propriedade Cenários Operacionais',
    tipo_periodo: 'safrinha',
    tipo_periodo_label: 'Safrinha',
    cultura: 'Milho',
    ano_agricola: '2025/2026',
    label: 'Safrinha • Milho • 2025/2026',
    data_inicio: '2026-01-15T12:00:00.000Z',
    data_fim: '2026-06-30T12:00:00.000Z',
    status: 'encerrada',
    observacoes: '[QA] Período encerrado e associado a registros do Caderno.',
    talhao_id: MOCK_V2_DEMO_QA_IDS.talhaoAtivo,
    talhao_nome: '[QA] Talhão sem geometria',
    criado_por_user_id: 'usr_colaborador_victor',
    criado_por_nome: 'Victor',
    criado_em: '2026-01-10T12:00:00.000Z',
    atualizado_em: '2026-07-01T12:00:00.000Z',
    registro_status: 'ativo',
    origem: 'local',
    versao: 1,
  },
  {
    id: 'periodo_qa_safra_algodao_em_andamento',
    propriedade_id: MOCK_V2_DEMO_QA_IDS.propriedadeOperacional,
    nome_propriedade: '[QA] Propriedade Cenários Operacionais',
    tipo_periodo: 'safra',
    tipo_periodo_label: 'Safra',
    cultura: 'Algodão',
    ano_agricola: '2025/2026',
    label: 'Safra • Algodão • 2025/2026',
    data_inicio: '2026-04-01T12:00:00.000Z',
    data_fim: '2026-09-15T12:00:00.000Z',
    status: 'em_andamento',
    observacoes: '[QA] Período em andamento.',
    criado_por_user_id: 'usr_colaborador_victor',
    criado_por_nome: 'Victor',
    criado_em: '2026-04-01T12:00:00.000Z',
    atualizado_em: '2026-08-01T12:00:00.000Z',
    registro_status: 'ativo',
    origem: 'local',
    versao: 1,
  },
  {
    id: 'periodo_qa_removido',
    propriedade_id: MOCK_V2_DEMO_QA_IDS.propriedadeOperacional,
    nome_propriedade: '[QA] Propriedade Cenários Operacionais',
    tipo_periodo: 'safra',
    tipo_periodo_label: 'Safra',
    cultura: 'Teste removido',
    ano_agricola: '2024/2025',
    label: 'Safra • Teste removido • 2024/2025',
    status: 'encerrada',
    observacoes: '[QA] Registro removido que não deve aparecer entre os períodos ativos.',
    criado_por_user_id: 'usr_colaborador_victor',
    criado_por_nome: 'Victor',
    criado_em: '2025-01-01T12:00:00.000Z',
    atualizado_em: '2026-08-01T12:00:00.000Z',
    removido_em: '2026-08-01T12:00:00.000Z',
    registro_status: 'removido',
    origem: 'local',
    versao: 1,
  },
];
